### ISSUE TITLE
Stackblitz demo won't run

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-angular-themes#126]
#### Describe the bug

[Stackblitz](https://stackblitz.com/github/brightlayer-ui/angular-showcase-demo/tree/master?file=README.md) says something like ```Type 'string' is not assignable to type 'boolean'.```

#### What is the expected behavior?

Should be nice and clean.

#### What are the steps to reproduce?
1. Go to master branch demo https://stackblitz.com/github/brightlayer-ui/angular-showcase-demo/tree/master
2. it wont run
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/8997218/200629665-2934ae1f-983f-478c-bee9-85eca3f915ec.png">

**Comment by emclaug2** [comment]
We'll talk about this issue in our next bug scrub but I'm going to lean towards closing & instead start linking out to our firebase deployment where needed: https://blui-angular-showcase.web.app/

**Comment by huayunh** [comment]
I agree. Please update readme before closing this issue.

**Comment by jeffvg** [comment]
going to update the links going out to firebase deploys. Open a new issue to track this.

**Comment by daileytj** [comment]
We have a deployed version of the angular showcase now. We will drop support for stackblitz.
