### ISSUE TITLE
NG 15 themes should match the legacy themes

### ISSUE THREAD

**Issue by daileytj** [etn-ccis/blui-angular-themes#156]
#### Describe the desired feature/functionality
After updating to NG15 and Angular Material v15, Angular Material components, and Brightlayer UI components should still look the same as they did on v14.

#### Is this request related to a current issue?
https://github.com/etn-ccis/blui-angular-showcase-demo/pull/303#issuecomment-1446926196

**Comment by joebochill** [comment]
@daileytj is this something we need an issue for, or should it just be part of the acceptance criteria for the PR that is still open? I.e., are we going to accept that PR as-is and then take this issue to handle cleanup?

**Comment by daileytj** [comment]
> @daileytj is this something we need an issue for, or should it just be part of the acceptance criteria for the PR that is still open? I.e., are we going to accept that PR as-is and then take this issue to handle cleanup?

The PR that is (was) open was a showcase-demo project. In order to fix these properly we will need updates to the theme so I wrote this issue to capture the work that still needs to be done before officially publishing.

**Comment by JeffGreiner-eaton** [comment]
I tried finding an open issue for this but didn't. 
The .cdk-overlay-backdrop-showing.blui-user-menu-bottomsheet-backdrop is getting trumped by .blui-blue .cdk-overlay-backdrop.cdk-overlay-backdrop-showing and setting opacity to 1 but instead should be .5 and displaying a solid background

![image](https://github.com/etn-ccis/blui-angular-themes/assets/119693939/c11819b9-e4c0-4731-a0ec-0813d3044f8c)

**Comment by JeffGreiner-eaton** [comment]
Noticed while running NG showcase demo from feature/migrate-to-ng15 and this is old carry over issue.

![image](https://github.com/etn-ccis/blui-angular-themes/assets/119693939/35f76863-8020-40e7-a99e-c6c86357dd3f)

![image](https://github.com/etn-ccis/blui-angular-themes/assets/119693939/c6fb28ab-455b-4906-99bf-eb5f24764bcd)
