### ISSUE TITLE
Support for Angular 17 with version 16 Material package

### ISSUE THREAD

**Issue by RyanPetrilla-eaton** [etn-ccis/blui-angular-themes#208]
#### Describe the desired feature/functionality
Eaton's Bid Manager development team has been using the brightlayer-ui/angular-themes package as part of our styling.  We would like to upgrade to Angular 17 while staying on the legacy version 16 Angular Material components.  The dependencies for this package need to be updated to allow an Angular CLI version of 17 with a Material package version of 16.

#### Additional Context (where / how would this be used)
Our plan is to eventually phase out the use of this package and create our own components for use with the new Material 3 standard. But for now, we would like to be able to continue with what we have while upgrading to Angular 17. 

#### Is this request related to a current issue?
Yes, we get a dependency error when trying to upgrade to Angular 17.

#### Suggested implementation details
Since the Material package will remain on the final version 16 release (16.2.12), I don't think we need any actual development work other than an update of the dependencies.

**Comment by joebochill** [comment]
The Angular themes do not have a dependency on @angular/core (they are just a collection of scss style sheets). They do have a peerDependency on @angular/material, but these peerDependency can already be satisfied by @angular/material version 15 or 16, so you should be fine to use the existing version of themes if you plan to combine angular 17 wth angular material 16.
