### ISSUE TITLE
Adjust Chip Mixin to use correct Accent Color

### ISSUE THREAD

**Issue by emclaug2** [etn-ccis/blui-angular-themes#72]
#### Describe the bug
Our mixin for the styling mat chips is using the incorrect palette color for accent chips.
In the image below, I've created a custom theme that uses green as primary, blue as accent, red as warn.

#### What is the expected behavior?

The accent chips should have no reference to the color green & should be blue in all variants. 
Specifically see the stroked accent chips, the background is a shade of green. 

#### What are the steps to reproduce?
Run the themes demo, but update the accent color palette to be a custom color (yellow, purple) and observe it not being used in the showcase chip example.

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/6538289/152030522-9a307cda-533a-4da0-9413-7a2b3243cd5b.png)

#### Environment

Windows Chrome
		
#### Anything else to add?
No

**Comment by jeffvg** [comment]
we can update this later
