### ISSUE TITLE
Dark theme blue drawer header should use white text

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-angular-themes#79]
#### Describe the bug
The text inside of a `<blui-drawer-header>` is the incorrect color. 

#### What is the expected behavior?
Should be white50. Anything on blue should be white50 in dark theme

#### How to recreate
1.  Navigate to the showcase app, [here](https://blui-angular-showcase.web.app/).
2. Enable dark mode
3. Observe the DrawerHeader (very carefully) and notice that it is the incorrect color. 

#### Proof
![image](https://user-images.githubusercontent.com/8997218/152414083-de44048c-81f1-4cf0-882f-7532e6e02442.png)
The text is black50

**Comment by emclaug2** [comment]
The icon should also be white[50]
